name: flutter_agendamento_pet
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  path: ^1.8.0

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  validators: ^3.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fundo.jpg
    - assets/images/fundo-marrom.jpg
    - assets/images/fundo-pet.jpg
